serverName: "proxy"
discord:
  enabled: false
  token: "change me."
  watching: "The Servers"
socket:
  trusted-token: "generate"
  client:
    address: "localhost"
    port: 8080
  server:
    address: "localhost"
    port: 8081